spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: null
  h2:
    console:
      enabled: true
  batch:
    initializer:
      enabled: true
    job:
      enabled: false
      
management:
  security:
    enabled: false